verifyStoreIntegrity: true
strictSsl: true
minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
blockExoticSubdeps: true
strictDepBuilds: true
dangerouslyAllowAllBuilds: false
verifyDepsBeforeRun: error
preferFrozenLockfile: true
savePrefix: ''
engineStrict: true
trustPolicy: no-downgrade
resolutionMode: time-based
sideEffectsCache: false
useBetaCli: false
updateNotifier: true
ignoreScripts: true
packageImportMethod: clone-or-copy
